name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: 1.68.2

jobs:
  lint-toml-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Cargo.toml linter
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-toml-lint
          version: "0.1.1"

      - name: Run Cargo.toml linter
        run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          [
            "airdrop",
            "AMM",
            "auctions/english-auction",
            "DAO",
            "escrow",
            "fractional-NFT",
            "fundraiser",
            "games/TicTacToe",
            "multisig-wallet",
            "name-registry",
            "NFT",
            "oracle",
            "OTC-swap-predicate",
            ".devops/.template",
            "timelock",
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Init rust cache
        uses: Swatinem/rust-cache@v2

      - name: Cache nix-cache locally
        id: cache-nix
        uses: actions/cache@v2.1.0
        with:
          # See https://stackoverflow.com/questions/59269850.
          path: |
              ~/nix/store
              ~/nix/bin
          key: ${{ runner.os }}-forc-0-39-0

      - name: Install fuel toolchain
        env: 
          CACHE_HIT:  ${{ steps.cache-nix.outputs.cache-hit }}
        uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-substituters = https://fuellabs.cachix.org
            extra-trusted-public-keys = fuellabs.cachix.org-1:3gOmll82VDbT7EggylzOVJ6dr0jgPVU/KMN6+Kf8qx8=
      - run: |
          NIX_STORE=/nix/store
          if [[ "$CACHE_HIT" != 'true' ]]; then
            nix profile install github:fuellabs/fuel.nix#forc-0-39-0
            mkdir -p ~/nix/store
            sudo cp --force --recursive $NIX_STORE/* ~/nix/store/
          else
            sudo mkdir -p $NIX_STORE
            sudo cp --force --recursive ~/nix/store/* $NIX_STORE/
          fi
